name = "Thmpa"
license = "MIT"
licenselink = "https://github.com/.../.../LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]

[author]
  name = "swortain"
  homepage = "makerpapa.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
